-- Supabase Support Lab schema

create table if not exists public.support_tickets (
    id bigint generated by default as identity primary key,
    customer_email text not null,
    subject text not null,
    status text not null default 'open',
    priority text not null default 'medium',
    created_at timestamptz not null default now()
);

create table if not exists public.ticket_updates (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null
        references public.support_tickets(id)
        on delete cascade,
    update_text text not null,
    created_at timestamptz not null default now()
);

alter table public.support_tickets enable row level security;
alter table public.ticket_updates enable row level security;
