-- Supabase Support Lab schema (Version 2)
--
-- This lab uses synthetic UUIDs so RLS behavior can be tested without writing
-- directly to Supabase's protected auth.users table. In a production schema,
-- owner_id would normally reference auth.users(id) or a trusted profiles table.

create table if not exists public.support_tickets (
    id bigint generated by default as identity primary key,
    owner_id uuid not null,
    customer_email text not null,
    subject text not null,
    status text not null default 'open'
        check (status in ('open', 'investigating', 'resolved')),
    priority text not null default 'medium'
        check (priority in ('low', 'medium', 'high', 'critical')),
    created_at timestamptz not null default now()
);

create table if not exists public.ticket_updates (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null
        references public.support_tickets(id)
        on delete cascade,
    update_text text not null,
    created_at timestamptz not null default now()
);

alter table public.support_tickets enable row level security;
alter table public.ticket_updates enable row level security;

-- Grants decide which operations a role may attempt. RLS policies below decide
-- which rows are visible. Keep grants and policies intentionally separate.
revoke all on table public.support_tickets from anon, authenticated;
revoke all on table public.ticket_updates from anon, authenticated;

-- anon retains SELECT only to reproduce the successful-but-empty RLS symptom.
-- No anon policy is present in the secure final state, so zero rows are visible.
grant select on table public.support_tickets to anon;
grant select on table public.support_tickets to authenticated;
grant select on table public.ticket_updates to authenticated;

comment on column public.support_tickets.owner_id is
'Synthetic Auth UID used for lab RLS tests. Production designs should normally reference a trusted identity table.';
